name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: |
          gradle wrapper --gradle-version 8.8
          ./gradlew --no-daemon clean build -x test
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: EssentialsLite-jar
          path: build/libs/*.jar
